
    # Global LLM configuration
    [llm]
    model = "doubao-1-5-pro-32k-250115"
    base_url = "https://ark.cn-beijing.volces.com/api/v3"
    api_key = "ea427448-d8fb-4ab3-a403-9a57d13af342"
    temperature = 0.0

    # Optional configuration for specific LLM models
    #[llm.vision]
    #model = "doubao-1-5-pro-32k-250115"
    #base_url = "https://ark.cn-beijing.volces.com/api/v3"
    #api_key = "ea427448-d8fb-4ab3-a403-9a57d13af342"
    